CREATE OR REPLACE PROCEDURE update_w_ba_f_scores()
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE 'Step 6: Populating womens big air finals scores...';

    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 1, 'Judge 1', 51);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 1, 'Judge 2', 45);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 1, 'Judge 3', 55);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 1, 'Judge 4', 43);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 1, 'Judge 5', 45);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 2, 'Judge 1', 79);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 2, 'Judge 2', 76);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 2, 'Judge 3', 85);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 2, 'Judge 4', 74);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 2, 'Judge 5', 76);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 3, 'Judge 1', 47);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 3, 'Judge 2', 44);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 3, 'Judge 3', 45);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 3, 'Judge 4', 43);
    PERFORM update_run_score(300, 'Kaitlyn', 'Adams', 'Finals', 3, 'Judge 5', 46);

    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 1, 'Judge 1', 60);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 1, 'Judge 2', 55);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 1, 'Judge 3', 58);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 1, 'Judge 4', 60);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 1, 'Judge 5', 58);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 2, 'Judge 1', 8);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 2, 'Judge 2', 6);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 2, 'Judge 3', 2);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 2, 'Judge 4', 11);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 2, 'Judge 5', 9);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 3, 'Judge 1', 30);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 3, 'Judge 2', 37);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 3, 'Judge 3', 45);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 3, 'Judge 4', 41);
    PERFORM update_run_score(300, 'Giada', 'Brienza', 'Finals', 3, 'Judge 5', 39);

    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 1, 'Judge 1', 76);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 1, 'Judge 2', 75);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 1, 'Judge 3', 80);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 1, 'Judge 4', 80);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 1, 'Judge 5', 78);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 2, 'Judge 1', 82);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 2, 'Judge 2', 72);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 2, 'Judge 3', 80);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 2, 'Judge 4', 76);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 2, 'Judge 5', 72);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 3, 'Judge 1', 7);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 3, 'Judge 2', 18);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 3, 'Judge 3', 22);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 3, 'Judge 4', 27);
    PERFORM update_run_score(300, 'Lily', 'Dhawornvej', 'Finals', 3, 'Judge 5', 19);

    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 1, 'Judge 1', 12);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 1, 'Judge 2', 9);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 1, 'Judge 3', 10);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 1, 'Judge 4', 14);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 1, 'Judge 5', 12);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 2, 'Judge 1', 8);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 2, 'Judge 2', 8);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 2, 'Judge 3', 2);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 2, 'Judge 4', 13);
    PERFORM update_run_score(300, 'Rongxi', 'Jin', 'Finals', 2, 'Judge 5', 9);

    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 1, 'Judge 1', 50);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 1, 'Judge 2', 50);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 1, 'Judge 3', 44);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 1, 'Judge 4', 40);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 1, 'Judge 5', 47);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 2, 'Judge 1', 82);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 2, 'Judge 2', 79);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 2, 'Judge 3', 82);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 2, 'Judge 4', 75);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 2, 'Judge 5', 73);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 3, 'Judge 1', 62);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 3, 'Judge 2', 60);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 3, 'Judge 3', 66);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 3, 'Judge 4', 69);
    PERFORM update_run_score(300, 'Hahna', 'Norman', 'Finals', 3, 'Judge 5', 61);

    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 1, 'Judge 1', 78);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 1, 'Judge 2', 80);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 1, 'Judge 3', 88);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 1, 'Judge 4', 82);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 1, 'Judge 5', 80);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 2, 'Judge 1', 13);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 2, 'Judge 2', 19);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 2, 'Judge 3', 33);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 2, 'Judge 4', 26);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 2, 'Judge 5', 24);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 3, 'Judge 1', 73);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 3, 'Judge 2', 69);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 3, 'Judge 3', 44);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 3, 'Judge 4', 65);
    PERFORM update_run_score(300, 'Juliette', 'Pelchat', 'Finals', 3, 'Judge 5', 63);

    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 1, 'Judge 1', 17);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 1, 'Judge 2', 11);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 1, 'Judge 3', 16);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 1, 'Judge 4', 18);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 1, 'Judge 5', 22);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 2, 'Judge 1', 16);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 2, 'Judge 2', 10);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 2, 'Judge 3', 16);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 2, 'Judge 4', 11);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 2, 'Judge 5', 20);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 3, 'Judge 1', 58);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 3, 'Judge 2', 48);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 3, 'Judge 3', 56);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 3, 'Judge 4', 46);
    PERFORM update_run_score(300, 'Courtney', 'Rummel', 'Finals', 3, 'Judge 5', 50);

    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 1, 'Judge 1', 49);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 1, 'Judge 2', 40);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 1, 'Judge 3', 45);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 1, 'Judge 4', 44);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 1, 'Judge 5', 43);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 2, 'Judge 1', 44);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 2, 'Judge 2', 49);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 2, 'Judge 3', 46);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 2, 'Judge 4', 52);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 2, 'Judge 5', 52);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 3, 'Judge 1', 17);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 3, 'Judge 2', 17);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 3, 'Judge 3', 22);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 3, 'Judge 4', 17);
    PERFORM update_run_score(300, 'Juliette', 'Vallerand', 'Finals', 3, 'Judge 5', 23);

    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 1, 'Judge 1', 80);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 1, 'Judge 2', 80);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 1, 'Judge 3', 85);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 1, 'Judge 4', 84);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 1, 'Judge 5', 83);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 2, 'Judge 1', 83);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 2, 'Judge 2', 76);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 2, 'Judge 3', 85);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 2, 'Judge 4', 74);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 2, 'Judge 5', 69);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 3, 'Judge 1', 22);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 3, 'Judge 2', 35);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 3, 'Judge 3', 36);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 3, 'Judge 4', 31);
    PERFORM update_run_score(300, 'Shirui', 'Xiong', 'Finals', 3, 'Judge 5', 30);

    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 1, 'Judge 1', 15);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 1, 'Judge 2', 13);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 1, 'Judge 3', 12);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 1, 'Judge 4', 10);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 1, 'Judge 5', 18);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 2, 'Judge 1', 84);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 2, 'Judge 2', 84);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 2, 'Judge 3', 88);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 2, 'Judge 4', 88);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 2, 'Judge 5', 87);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 3, 'Judge 1', 41);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 3, 'Judge 2', 41);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 3, 'Judge 3', 42);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 3, 'Judge 4', 49);
    PERFORM update_run_score(300, 'Xiaonan', 'Zhang', 'Finals', 3, 'Judge 5', 40);

    RAISE NOTICE 'Step 6: Womens big air finals scores populated successfully.';
END;
$$;